services:
  mysql:
    image: mysql:8.0
    container_name: sudowallet-mysql

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sudowallet
      MYSQL_USER: sudowallet_user
      MYSQL_PASSWORD: sudowallet_password
    
    ports:
      - 3306:3306
    volumes: 
      - mysql-data:/var/lib/mysql
    restart: always
  redis:
    image: redis:6.0-alpine
    container_name: sudowallet-redis
    ports:
      - 6379:6379
    restart: always
  mailhog:
    image: mailhog/mailhog:latest
    container_name: sudowallet-mailhog
    ports:
      - 1025:1025 # for SMTP port
      - 8025:8025 # for web UI port
    restart: always
volumes:
 mysql-data: